### PR TITLE
Attributes indices and Small fix to Instance's toString()

### PR DESCRIPTION
**Pull request by jaycwb**
- New methods for setting and testing for missing values
- New method for method to setValue(Attribute att, double value)
- New structure for maintaining attributes’ indices
- Small fix on Instance toString method to correctly output missing values

### CODE REVIEW

**Comment by abifet** [comment]
+1

**Comment by abifet** [comment]
Diamond types are not supported in Java 1.6. Plese, can you modify this line? 
this.hsAttributesIndices = new HashMap<>();
Thanks!

**Comment by abifet** [comment]
Done!

**Comment by jaycwb** [comment]
Hi Albert, 

Sorry for the delay. I see you already changed the line. I'll keep that in mind in future commits.

Cheers, Jean

**Pull request merged**
