### PR TITLE
DataSet should not be set to null

### PR DESCRIPTION
**Pull request by yuhang-lin**
This line of code causes "null pointer exception"

### CODE REVIEW

**Comment by richard-moulton** [comment]
The first commit in this pull request (commit ce8b495cec9eac6a3e1c15b0bdd40dcd67fefe02) solves the same issue as pull request #81.

**Comment by yuhang-lin** [comment]
But why is the pull request #81 still open?

**Comment by richard-moulton** [comment]
I am not sure what the process is for integrating pull requests from the community into MOA. I have not received any feedback regarding pull request #81.

**Comment by yuhang-lin** [comment]
No feedback is normal because few people are working on this project. Many functions are not yet implemented and there are so many bugs. I feel really frustrated.

**Comment by abifet** [comment]
@yuhang-li Thanks for giving some feedback about the project.

We are working on a new release for MOA for next week. Many people are working on this project. New important and recent algorithms are going to be in this new release as SAM-Knn, winner of the best paper award at ICDM 2016, and Adaptive Random Forests.

Projects have always things to improve. Please, can you help on identifying the bugs? We'll be vey grateful for your help.

**Pull request merged**
