### PR TITLE
Add the RCD classifier

### PR DESCRIPTION
**Pull request by pmgj**
The RCD classifier and the multivariate non-parametric statistical tests that it uses are included in this pull request. It is based on the paper _Gonçalves Jr, Paulo Mauricio, and Roberto Souto Maior De Barros. "RCD: A recurring concept drift framework." Pattern Recognition Letters 34.9 (2013): 1018-1025._

### CODE REVIEW

**Comment by abifet** [comment]
Thanks! Please add license headers and javadoc documentation to the statistical test files.

**Comment by pmgj** [comment]
License headers and javadoc documentation included.

**Comment by abifet** [comment]
Thanks!

**Comment by abifet** [comment]
The source code is not compiling. It seems that it needs external libraries.

**Pull request merged**
