### PR TITLE
Add DWM classifier

### PR DESCRIPTION
**Pull request by pmgj**
Add the Dynamic weighted majority algorithm, as proposed by J. Zico Kolter and Marcus A. Maloof. Dynamic weighted majority: An ensemble method for drifting concepts. The Journal of Machine Learning Research, 8:2755-2790, December 2007. ISSN 1532-4435. URL http://dl.acm.org/citation.cfm?id=1314498.1390333.

### CODE REVIEW

**Comment by abifet** [comment]
Thanks! Please add the license header and a test file.

**Comment by pmgj** [comment]
What are the characteristics of the test file?

**Comment by abifet** [comment]
It's very simple. Take a look at moa/src/test/java/moa/classifiers/bayes/NaiveBayesTest.java for example.

**Comment by abifet** [comment]
+1

**Pull request merged**
