### PR TITLE
Added AdaGrad implementation based on the SGD implementation.

### PR DESCRIPTION
**Pull request by henrygouk**

### CODE REVIEW

**Comment by csalperwyck** [comment]
Hi,

Just one question, is it really different from the SGD class?
https://github.com/Waikato/moa/blob/master/moa/src/main/java/moa/classifiers/functions/SGD.java

A fast look seems to show that lots of code are in common.

If it is a bit different, perhaps you could do a subclass or integrate your code inside.

@abifet what do you think?

**Comment by csalperwyck** [comment]
@henrygouk thx!

**Comment by abifet** [comment]
Can you add the reference to the original paper? Thanks!

**Comment by abifet** [comment]
Thanks! +1

**Pull request merged**
