### PR TITLE
Local Adaptive Streaming Tree

### PR DESCRIPTION
**Pull request by danielnowakassis**
Hi.

We proposed an adaptive splitting mechanism, where a change detector monitors the error rate or data distribution purity (parameter) of the leaf node to determine the split point (and if merit > 0). It had some good results against SOTA decision trees.

The published paper is here: https://dl.acm.org/doi/10.1145/3605098.3635899

You can access the paper pdf here :
https://drive.google.com/file/d/1vxfDEEyOPacWD2nKocQzjCRFLBZl7tUH/view?usp=sharing

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @danielnowakassis , thanks for your contribution, we will be looking into it shortly. 
@nuwangunasekara could you please review this PR? I will be a bit busy this next few days with ECML organisation / presentations

**Comment by nuwangunasekara** [comment]
@hmgomes I could have a look 🙂

**Comment by nuwangunasekara** [comment]
@hmgomes and @danielnowakassis : RR looks okay 
We just need the test files

To run tests 
`mvn clean package -Dmaven.javadoc.skip=true -Dskip.pdf=true -Dtest="TestClassName"`

Note:- 
Currently all tests 
`mvn clean package -Dmaven.javadoc.skip=true -Dskip.pdf=true`
pass on JDK 11

**Comment by danielnowakassis** [comment]
Hi @nuwangunasekara and @hmgomes. 

> @hmgomes I could have a look 🙂 @danielnowakassis : while I look at `moa/src/main/java/moa/classifiers/trees/LAST.java` , you might want to add a unit test like in `moa/src/test/java/moa/classifiers/trees/HoeffdingTreeTest.java` along with a reference file like `moa/src/test/resources/moa/classifiers/trees/HoeffdingTree.ref` :)

Ok. I did the commits. If you have any questions, don't hesitate to contact me :)

**Comment by nuwangunasekara** [comment]
Thanks @danielnowakassis !
I am fine with the changes. 
Assume you ran the test for the second time to check whether it produces identical results?


Will leave @hmgomes to merge things.

**Comment by danielnowakassis** [comment]
> Thanks @danielnowakassis ! I am fine with the changes. Assume you ran the test for the second time to check whether it produces identical results?

@nuwangunasekara Yes, I did.

**Comment by nuwangunasekara** [comment]
Thanks @danielnowakassis 🙂

**Review by nuwangunasekara — APPROVED** [review]

**Comment by danielnowakassis** [comment]
Hi  @nuwangunasekara and @hmgomes.
Any news in this PR?

**Comment by nuwangunasekara** [comment]
Hi @danielnowakassis 

I see that you have updated the PR after I approved it. I assume the test refs are still valid :)

If that's the case we are waiting on @hmgomes  to merge it 🙂

He was busy with back to back conferences.
Should be back in office now.

**Comment by danielnowakassis** [comment]
They are still valid :) 

Ok, waiting for @hmgomes :)

**Comment by hmgomes** [comment]
thanks for the contribution @danielnowakassis and thanks @nuwangunasekara for the review

**Pull request merged**
